"""
List Generated from https://beckchris.com/history/the-55-most-important-events-in-human-history/
"""

world_history = [
"The Agricultural Revolution: Humans Domesticate Plants and Animals",
"The First Cities Emerge in Mesopotamia",
"The First Wheeled Vehicles Appear in Mesopotamia",
"The First Writing Systems Appear in Mesopotamia",
"The Ancient Egyptians Build the Great Pyramid of Giza for Pharaoh Khufu",
"The Origin and Development of Modern Alphabets",
"Babylonian King Hammurabi Issues the Code of Hammurabi, One of the Earliest Legal Codes",
"As Knowledge of Iron Metallurgy Spreads, the Bronze Age Ends and the Iron Age Begins",
"The Rise and Fall of Ancient Greek Civilization",
"The Rise and Fall of Ancient Roman Civilization:",
"The Life of the Buddha and Birth of Buddhism",
"The Life of Confucius and Birth of Confucianism",
"Alexander the Great Creates an Immense Empire",
"Unification of China under Emperor Qin Shi Huang",
"The Birth of the Modern Calendar",
"The Life of Jesus and the Birth of Christianity",
"The Life of Muhammad and the Birth of Islam",
"Pope Leo III Crowns Charlemagne, Carolingian King of the Franks and the Lombards, as the First Holy Roman Emperor",
"The Invention of Gunpowder and its Use in Weaponry",
"Norse Explorers Discover and Colonize New Lands in the North Atlantic",
"Norman Conquest of England",
"The First University Is Established, at Bologna",
"The First Crusade",
"King Suryavarman II of the Khmer Empire Builds Angkor Wat",
"Shogun Minamato no Yorimoto Overthrows the Taira Emperor",
"Genghis Khan Establishes a Vast Mongol Empire",
"English Nobles Force King John to Sign the Magna Charta",
"Europe Hears Tales of the Far East From Marco Polo",
"The Rise and Fall of the Aztec Civilization",
"The Black Death (Bubonic Plague) Devastates Europe",
"The Start of the Renaissance",
"The Inca People Create an Empire",
"Johannes Gutenberg Invents a Printing Press",
"The Ottoman Turks Take Constantinople, Marking the Fall of the Eastern Roman",
"Christopher Columbus Arrives in the West Indies and Claims the Land for Spain",
"Portuguese Explorer Vasco da Gama Finds a Sea Route from Europe to India",
"Spanish and English Explorers Returning to Europe Bring Back New World Foods",
"The Slave Trade: Enslaved African People Are Brought to the Americas",
"Martin Luther Sends his 95 Theses to the Archbishop of Mainz",
"Suleiman the Magnificent Rules Ottoman Empire During Period of Great Expansion",
"Ferdinand Magellan’s Expedition Is the First to Circumnavigates the Globe",
"Polish Scientist Nicolaus Copernicus’s On the Revolutions of the Celestial Spheres",
"England under Queen Elizabeth I Repels a Spanish Invasion by Defeating the Spanish Armada",
"William Shakespeare Writes Hamlet",
"English Colonists Establish Their First Permanent Settlement in the New World at Jamestown, Virginia",
"Galileo Galilei Publishes The Starry Messenger",
"England Undergoes A Civil War",
"Mughal Emperor Shah Jahan Builds the Taj Mahal",
"The Power of Steam is Harnessed in the Steam Engine",
"Isaac Newton’s Principia Mathematica",
"Innovations in the British Textile Industry Spark the Industrial Revolution",
"The Boston Tea Party",
"The Start and End of American Revolution",
"The Start and End of French Revolution",
"The Start of Medical Revolution",
"The Birth of Rail Transport",
"The Napoleonic Wars",
"The End of the African Slave Trade and Abolition of Slavery",
"Spain’s Colonies in Central and South America Fight for and Win Independence",
"The Invention of the Telegraph Revolutionizes Communication",
"Karl Marx and Friedrich Engels Publish The Communist Manifesto",
"Charles Darwin publishes On the Origin of Species",
"The American Civil War",
"The Meiji Restoration: Tokugawa Yoshinobu Abdicates to Emperor Meiji, Ending Shogun Rule in Japan",
"Opening of the Suez Canal",
"Alexander Graham Bell Patents the Telephone",
"European Powers Colonize Africa",
"The Suffrage Movement: Women Fight For the Right to Vote",
"The Invention of Radio",
"The Discovery of X-Rays",
"Orville & Wilbur Wright Fly the First Heavier-than-Air Powered Aircraft",
"After Defeating Russia in the Russo-Japanese War, Japan Is Recognized as a World Power",
"Albert Einstein’s Annus Mirabilis",
"Start and End of World War I",
"The Russian Revolution",
"The Invention of Television",
"Black Tuesday: The Stock Market Crash of 1929",
"The Rise of Adolf Hitler and the Nazis",
"Start and End of World War II",
"The Invention of the Digital Electric Computer",
"India Obtains Its Independence from the UK",
"The Discovery of the Double Helical Structure of DNA",
"Assassination of Martin Luther King, Jr.",
"US Enters the Vietnam War",
"Soviet Union Launches Sputnik, First Man-Made Satellite,",
"FDA Approves First Contraceptive Pill",
"U.S. President John F. Kennedy Is Assassinated",
"Apollo 11 Astronauts Neil Armstrong and Buzz Aldrin Land on the Moon",
"The Birth of the Internet",
"Al Qaeda Terrorists Attack New York City",
]